backend:
  name: git-gateway
  branch: master 

media_folder: "public/images/"
public_folder: "/images/"

collections:
  - name: "fond_accueil" 
    label: "Fond_accueil"
    folder: "_posts/background"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "fond_accueil"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "Image", widget: "image"}
